#!/bin/bash

# Convox Tool
# Paul Oram - Jun 2019

cacheFile=".cache"
racksVariable="racks"
apps=$(cat $cacheFile | grep -v $racksVariable | cut -d "=" -f1)

sourceCache() {
    if [ -f $cacheFile ]; then
        source $cacheFile; else
        echo "Please run 'convoxtool -u' to update the cache"
        exit 1
    fi
}

readRackArray() {
    eval echo "\${$1[@]}"
}

readSingleArray() {
    app=$(eval echo "\${$1}")
}

cacheRack() {
    counter=1
    for r in $(convox racks | awk '{print $1}' | grep -v NAME); do
        echo $racksVariable"["$counter"]="$r
        let counter=counter+1
    done
}

returnRack() {
    sourceCache
    for r in $(readRackArray $racksVariable); do
        echo $r
    done
}

returnRackStatus() {
    convox rack --rack=$1 | grep Status | awk '{print $2}'
}

updateRack() {
    for r in $(returnRack); do
        if [[ $(returnRackStatus $r) == running ]]; then
            echo "Updating rack: $r"
            convox rack update --rack=$r
            sleep 15
            while [ $(returnRackStatus $r) != running ]; do
                echo "$r is still updating"
                sleep 300
            done
            echo "Rack update for $r complete!"
        else
            echo "Rack $r is not in a state to be updated"
        fi
    done
}

cacheApps() {
    for r in $(returnRack); do
        counter=1
        for a in $(convox apps --rack=$r | grep -v APP |awk '{print $1}'); do 
            echo $r"["$counter"]="$a | cut -d '/' -f2 | tr -d "-"
            let counter=counter+1
        done
    done
}

returnApps() {
    sourceCache
    for r in $apps; do
        readRackArray $r
    done
}

matchApp() {
    sourceCache
    for r in $apps; do
        readSingleArray $r
        if [[ $app =~ $1 ]]; then
            echo "Match $app found in ${r:0:${#r}-3}"
        fi
    done
}

help() {
    echo "Simple convox tool to cache rack information, and find applications.

Usage:
    convoxtool -a                         return a list of all applications
    convoxtool -c                         create/update cache
    convoxtool -f [application...]        find application
    convoxtool -h                         help menu
    convoxtool -r                         return a list of convox racks
    convoxtool -u                         update all convox racks

Examples:
    convoxtool -a shoebox

Further help:
    convox            list all 'convox' commands"
}

case $1 in
    -a) 
        returnApps;;
    -c) 
        cacheRack > $cacheFile
        cacheApps >> $cacheFile;;
    -h)
        matchApp $2;;
    -h)
        help;;
    -r) 
        returnRack;;
    -u)
        updateRack;;
    *) 
        help
        exit 1
esac
