#!/bin/bash

# Convox Tool
# Paul Oram - Jun 2019

cacheFile=".cache"
racksVariable="racks"

sourceCache() {
    if [ -f $cacheFile ]; then
        source $cacheFile; else
        echo "Please run 'convoxtool -u' to update the cache"
        exit 1
    fi
}

readRackArray() {
    eval echo "\${$1[@]}"
}

readSingleArray() {
    app=$(eval echo "\${$1}")
}

cacheRack() {
    counter=1
    for r in $(convox racks | awk '{print $1}' | grep -v NAME); do
        echo $racksVariable"["$counter"]="$r
        let counter=counter+1
    done
}

returnRack() {
    sourceCache
    for r in $(readRackArray $racksVariable); do
        echo $r
    done
}

cacheApps() {
    for r in $(returnRack); do
        counter=1
        for a in $(convox apps --rack=$r | grep -v APP |awk '{print $1}'); do 
            echo $r"["$counter"]="$a | cut -d '/' -f2 | tr -d "-"
            let counter=counter+1
        done
    done
}

returnApp() {
    sourceCache
    for r in $(cat $cacheFile | grep -v $racksVariable | cut -d "=" -f1); do
        readSingleArray $r
        if [[ $app =~ $1 ]]; then
            echo "Match $app found in ${r:0:${#r}-3}"
        fi
    done
}

help() {
    echo "Simple convox tool to cache rack information, and find applications.

Usage:
    convoxtool -h
    convoxtool -u                         update cache
    convoxtool -a [application...]        find application

Examples:
    convoxtool -a shoebox

Further help:
    convox            list all 'convox' commands"
}

case $1 in
    -u) 
        cacheRack > $cacheFile
        cacheApps >> $cacheFile;;
    -a) 
        returnApp $2;;
    -r) 
        returnRack;;
    -h)
        help;;
    *) 
        help
        exit 1
esac
